<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>THE LEAGUE</title>
    
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Roboto:ital,wght@0,300;0,400;0,700;1,300;1,400;1,700&family=Ubuntu:wght@700&display=swap" rel="stylesheet">
    
    <link rel="stylesheet" href="Style/css/style.css">
</head>
<body>

<header>
    <nav>
        <a href="index.php" class="logo">THE LEAGUE</a>
        <ul>
            <li><a href="index.php?page=teams">LES TEAMS</a></li>
            <li><a href="index.php?page=players">LES PLAYERS</a></li>
            <li><a href="index.php?page=matchs">LES MATCHS</a></li>
        </ul>
    </nav>
</header>