<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="preconnect" href="https://fonts.googleapis.com">
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
        <link href="https://fonts.googleapis.com/css2?family=Roboto:ital,wght@0,300;0,400;0,700;1,300;1,400;1,700&family=Ubuntu:wght@700&display=swap" rel="stylesheet">
 
</head>
<body>
    <header class="header">
       <a href="index.phtml">
        <li>the league</li>
    </header>
    <nav>
        <a href="teams.phtml" class="bouton-nav">teams</a>
        <a href="players.phtml" class="bouton-nav">players</a>
        <a href="matchs.phtml" class="bouton-nav">matchs</a>
    </nav>
    <div>
    <img src="../Style/Image/home_background_league.png" alt="image de fond" class="header-photo">
    <li>TOUT SUR LA LEAGUE</li>
    <li>les players, les teams et l'actu des matchs</li>
    </div>
    <div>
        <li>la team a la une</li>
    </div>
    <div>
        <li>les players a la une</li>
    </div>
    <div>
        <li>le dernier match</li>
    </div>
</body>
</html>
