<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title></title>
</head>
<body>
    <header class="header">
    <a href="index.phtml">
    <li>the league</li>
    </header>

    <nav>
        <a href="teams.phtml" class="bouton-nav">teams</a>
        <a href="players.phtml" class="bouton-nav">players</a>
        <a href="matchs.phtml" class="bouton-nav">matchs</a>
    </nav>
</body>
    <div >

    </div>
</body>
</html>
